post:
  summary: Adding the product
  oprationId: addingProductByProductId
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schema/products_req.yaml"
  responses:
    "200":
      description: Product added successfully
      content:
        application/json:
          schema:
            $ref: "../schema/successResponse.yaml"
    "404":
      description: Error adding the product
      content:
        application/json:
          schema:
            $ref: "../schema/errorResponse.yaml"
put:
  summary: Updating the product
  operationId: updateProductByProductId
  parameters:
  - name: shopId
    in: path
    required: true
    schema:
      type: string
  - name: inventoryId
    in: path
    required: true
    schema:
      type: string
  - name: productId
    in: path
    required: true
    schema:
      type: string
  responses:
    "200":
      description: Product successfully updated
      content:
        application/json:
          schema:
            $ref: "../schema/successResponse.yaml"
    "404":
      description: Error updating the product
      content:
        application/json:
          schema:
            $ref: "../schema/errorResponse.yaml"
delete:
  summary: Deleting the product
  operationId: deleteProductByProductId
  parameters:
  - name: shopId
    in: path
    required: true
    schema:
      type: string
  - name: inventoryId
    in: path
    required: true
    schema:
      type: string
  - name: productId
    in: path
    required: true
    schema:
      type: string
  responses:
    "200":
      description: Product deleted successfully
      content:
        application/json:
          schema:
            type: "../schema/successResponse.yaml"
    "404":
      description: Error deleting the product
      content:
        application/json:
          schema:
            type: "../schema/errorResponse.yaml"
