post:
  summary: Adding the product
  oprationId: AddingProductById
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schema/products_req.yaml"
  responses:
    "200":
      description: Product added successfully
      content:
        application/json:
          schema:
            $ref: "../schema/successResponse.yaml"
    "404":
      description: Error adding the product
      content:
        application/json:
          schema:
            $ref: "../schema/errorResponse.yaml"
get:
  summary: Getting the product
  operationId: GettingproductById
  parameters:
    name: productId
    in: path
    required: true
    schema:
      type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schema/products_req.yaml"
  responses:
    "200":
      description: Product fetched successfully
      content:
        application/json:
          schema:
            $ref: "../schema/products_req.yaml"
    "404":
      description: Error fetching the product
      content:
        application/json:
          schema:
            $ref: "../schema/errorResponse.yaml"
put:
  summary: Updating the product
  operationId: UpdateProductById
  parameters:
    name: productId
    in: path
    required: true
    schema:
      type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schema/products.yaml"
  responses:
    "200":
      description: Product successfully updated
      content:
        application/json:
          schema:
            $ref: "../schema/successResponse.yaml"
    "404":
      description: Error updating the product
      content:
        application/json:
          schema:
            $ref: "../schema/errorResponse.yaml"
delete:
  summary: Deleting the product
  operationId: DeleteProductById
  parameters:
    name: productId
    in: path
    required: true
    schema:
      type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schema/successResponse.yaml"
  responses:
    "200":
      description: Product deleted successfully
      content:
        application/json:
          schema:
            type: "../schema/successResponse.yaml"
    "404":
      description: Error deleting the product
      content:
        application/json:
          schema:
            type: "../schema/errorResponse.yaml"
