openapi: 3.0.0
info:
  title: api for billing system
  version: 0.1.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: "./schema/index.yaml"
paths:  
  /inventory:
    $ref: "./api/inventory_api.yaml"
  /shop:
    $ref: "./api/shop_api.yaml"
  /products:
    $ref: "./api/products_api.yaml"
  /allInventory:
    $ref: "./api/getAllInventory.yaml"
  /allProducts:
    $ref: "./api/getAllProducts.yaml"
  /allShops:
    $ref: "./api/getAllShops.yaml"
    