type: object
required:
  - shopId
  - inventoryId
  - productId
  - productname
  - type
  - price
properties:
  shopId:
    type: string
  inventoryId:
    type: string
  productId:
    type: string
  type:
    type: string
  price:
    type: number
